eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
  instance:
    prefer-ip-address: true
    hostname: localhost
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/customers/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: account-service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/accounts/**
              filters:
                - StripPrefix=1
                - JwtValidation

            - id: transaction-service
              uri: lb://TRANSACTION-SERVICE
              predicates:
                - Path=/api/transactions/**
              filters:
                - StripPrefix=1
                - JwtValidation


server:
  port: 8080